package harness

// Generated by https://quicktype.io

type ResourceGroups struct {
	Status        string             `json:"status"`
	Data          ResourceGroupsData `json:"data"`
	MetaData      interface{}        `json:"metaData"`
	CorrelationID string             `json:"correlationId"`
}

type ResourceGroupsData struct {
	TotalPages    int64                   `json:"totalPages"`
	TotalItems    int64                   `json:"totalItems"`
	PageItemCount int64                   `json:"pageItemCount"`
	PageSize      int64                   `json:"pageSize"`
	Content       []ResourceGroupsContent `json:"content"`
	PageIndex     int64                   `json:"pageIndex"`
	Empty         bool                    `json:"empty"`
	PageToken     interface{}             `json:"pageToken"`
}

type ResourceGroupsContent struct {
	ResourceGroup  ResourceGroup `json:"resourceGroup"`
	CreatedAt      int64         `json:"createdAt"`
	LastModifiedAt int64         `json:"lastModifiedAt"`
	HarnessManaged bool          `json:"harnessManaged"`
}

type ResourceGroup struct {
	Identifier         string                            `json:"identifier"`
	Name               string                            `json:"name"`
	Color              string                            `json:"color"`
	Tags               interface{}                       `json:"tags"`
	Description        string                            `json:"description"`
	AllowedScopeLevels []ResourceGroupsAllowedScopeLevel `json:"allowedScopeLevels"`
	IncludedScopes     []ResourceGroupsIncludedScope     `json:"includedScopes"`
	ResourceFilter     ResourceGroupsResourceFilter      `json:"resourceFilter"`
	AccountIdentifier  *RolesAccountIdentifier           `json:"accountIdentifier,omitempty"`
}

type ResourceGroupsIncludedScope struct {
	Filter            ResourceGroupsFilter    `json:"filter"`
	AccountIdentifier *RolesAccountIdentifier `json:"accountIdentifier,omitempty"`
	OrgIdentifier     *string                 `json:"orgIdentifier,omitempty"`
}

type ResourceGroupsResourceFilter struct {
	Resources           []ResourceGroupsResource `json:"resources"`
	IncludeAllResources bool                     `json:"includeAllResources"`
}

type ResourceGroupsResource struct {
	ResourceType    string                         `json:"resourceType"`
	Identifiers     []string                       `json:"identifiers"`
	AttributeFilter *ResourceGroupsAttributeFilter `json:"attributeFilter,omitempty"`
}

type ResourceGroupsAttributeFilter struct {
	AttributeName   string   `json:"attributeName"`
	AttributeValues []string `json:"attributeValues"`
}

type ResourceGroupsAccountIdentifier string

type ResourceGroupsAllowedScopeLevel string

const (
	ResourceGroupsAccount      ResourceGroupsAllowedScopeLevel = "account"
	ResourceGroupsOrganization ResourceGroupsAllowedScopeLevel = "organization"
)

type ResourceGroupsFilter string

const (
	ResourceGroupsExcludingChildScopes ResourceGroupsFilter = "EXCLUDING_CHILD_SCOPES"
	ResourceGroupsIncludingChildScopes ResourceGroupsFilter = "INCLUDING_CHILD_SCOPES"
)

type ResourceGroupsAPI interface {
	GetAllResourceGroups(format string, account string) (Entities, error)
}
