package harness

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"text/template"

	"github.com/aleksa11010/harness-api-wrapper/templates"
)

// Generated by https://quicktype.io

type UserGroups struct {
	Status        string        `json:"status"`
	Data          UserGroupData `json:"data"`
	MetaData      interface{}   `json:"metaData"`
	CorrelationID string        `json:"correlationId"`
}

type UserGroupData struct {
	TotalPages    int64              `json:"totalPages"`
	TotalItems    int64              `json:"totalItems"`
	PageItemCount int64              `json:"pageItemCount"`
	PageSize      int64              `json:"pageSize"`
	Content       []UserGroupContent `json:"content"`
	PageIndex     int64              `json:"pageIndex"`
	Empty         bool               `json:"empty"`
	PageToken     interface{}        `json:"pageToken"`
}

type UserGroupContent struct {
	AccountIdentifier   UserGroupAccountIdentifier `json:"accountIdentifier"`
	Identifier          string                     `json:"identifier"`
	Name                string                     `json:"name"`
	Users               []string                   `json:"users"`
	NotificationConfigs []interface{}              `json:"notificationConfigs"`
	ExternallyManaged   bool                       `json:"externallyManaged"`
	Description         string                     `json:"description"`
	Tags                interface{}                `json:"tags"`
	HarnessManaged      bool                       `json:"harnessManaged"`
	SsoLinked           bool                       `json:"ssoLinked"`
}

type UserGroupAccountIdentifier string

type UserGroupAPI interface {
	GetAllUserGroups(format string, account string) (Entities, error)
}

func (u UserGroups) FormatUserGroups() error {

	content := make([]json.RawMessage, 0)
	for _, userGroup := range u.Data.Content {
		group, err := json.Marshal(userGroup)
		if err != nil {
			fmt.Printf("error marshalling user group: %s", err)
		}
		content = append(content, json.RawMessage(group))
	}

	reportData, err := json.Marshal(content)
	if err != nil {
		fmt.Println("Unable to marshal json", err)
		return err
	}
	err = createUserGroupReport(reportData)
	if err != nil {
		fmt.Println("Unable to create a HTML output :", err)
		return err
	}
	return nil
}

func createUserGroupReport(content []byte) error {
	type ReportData struct {
		Header  string
		Content string
	}

	reportData := ReportData{
		Header:  "User Groups",
		Content: string(content),
	}

	userGroupsTemplate, err := fs.ReadFile(templates.EmbeddedFiles, "report.html")
	if err != nil {
		fmt.Printf("error reading user groups template: %s", err)
	}

	t, err := template.New("usergroups").Parse(string(userGroupsTemplate))
	if err != nil {
		fmt.Printf("error parsing user groups template: %s", err)
		return err
	}

	var output bytes.Buffer
	err = t.Execute(&output, reportData)
	if err != nil {
		fmt.Println(err)
		return err
	}

	if _, err := os.Stat("report"); os.IsNotExist(err) {
		err = os.Mkdir("report", 0755)
		if err != nil {
			panic("Unable to create directory")
		}
	}
	if _, err := os.Stat("report/data"); os.IsNotExist(err) {
		err = os.Mkdir("report/data", 0755)
		if err != nil {
			panic("Unable to create directory")
		}
	}

	file, err := os.OpenFile("./report/data/usergroups.html", os.O_TRUNC|os.O_CREATE|os.O_WRONLY, 0644)
	if err != nil {
		panic(err)
	}
	defer file.Close()

	_, err = file.Write(output.Bytes())
	if err != nil {
		panic(err)
	}

	return nil
}
